Fogl 1724
foglamp/foglamp-north-http pull request #11
Opened 2018-08-28 09:49 UTC by amarendra-dianomic

2018-08-30 09:05 UTC, praveen-garg commented on python/foglamp/plugins/north/http_north/http_north.py
> +        'order': '3'
is it being used?

2018-08-30 09:06 UTC, praveen-garg commented on python/foglamp/plugins/north/http_north/http_north.py
> +        "default": "False",
should be lowercase?

2018-08-30 09:07 UTC, praveen-garg requested changes
there is one unused config item and still has higher order than others, also boolen true false should be lowercase

2018-09-04 07:17 UTC, amarendra-dianomic commented
@praveen-garg seems that currently unused config item is set for future use in a TODO comment. Boolean value changed to lower case.

2018-09-04 07:29 UTC, praveen-garg commented
there is no shutdown so remove that TODO comment and this config item please.

2018-09-04 07:53 UTC, amarendra-dianomic commented
@praveen-garg feedback changes done. Pl check.

2018-09-04 07:59 UTC, praveen-garg commented
where are you using compression and timeout?

2018-09-04 08:10 UTC, praveen-garg commented on python/foglamp/plugins/north/http_north/http_north.py
> +        return is_data_sent, new_last_object_id, num_sent
else: 
 `        return is_data_sent, new_last_object_id, num_sent`

2018-09-04 08:46 UTC, amarendra-dianomic commented on python/foglamp/plugins/north/http_north/http_north.py
> +        return is_data_sent, new_last_object_id, num_sent
done. PL check.

2018-09-04 08:47 UTC, praveen-garg approved these changes

2018-09-04 08:47 UTC, merged